@startuml

participant UI as UI <<presentation>>
control Controller as Controller <<application>>
participant "PersistenceContext" as PersistenceContext <<Persistence>>
database RepositoryFactory as RepositoryFactory <<repository>>
database CollaboratorsRepository as RepositoryCollaborators <<repository>>

activate UI

UI->Controller : create()
activate Controller
UI -> Controller : listCollaborators()

Controller -> PersistenceContext: repositories()
activate PersistenceContext

PersistenceContext -> RepositoryFactory : create()
activate RepositoryFactory

deactivate PersistenceContext

RepositoryFactory -> RepositoryCollaborators : create()
deactivate RepositoryFactory

activate RepositoryCollaborators

Controller -> RepositoryCollaborators : findAll()

RepositoryCollaborators --> Controller :allCollaborators()
deactivate RepositoryCollaborators

Controller--> UI:
deactivate Controller

UI-> UI:show()
@enduml
